export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const POST_USER_SUCCESS = 'POST_USER_SUCCESS';

export const GET_REPORT_SUCCESS = 'GET_REPORT_SUCCESS';
